Use more strict type for schema
fastify/env-schema pull request #134
Opened 2022-09-25 13:25 UTC by klaseca

#### Checklist

- [x] run `npm run test` and `npm run benchmark`
- [x] tests and/or benchmarks are included
- [x] documentation is changed or added
- [x] commit message and code follows the [Developer's Certification of Origin](https://github.com/fastify/.github/blob/master/CONTRIBUTING.md#developers-certificate-of-origin-11)
      and the [Code of conduct](https://github.com/fastify/.github/blob/master/CODE_OF_CONDUCT.md)

2022-09-25 17:32 UTC, climba03003 requested changes
This library should accept any `JSON Schema` library.
For example `typebox`.

Can you add an integration test for 3rd party library?

2022-09-27 08:50 UTC, mcollina approved these changes
lgtm

2022-09-28 09:42 UTC, climba03003 approved these changes

2022-09-28 09:57 UTC, merged

2022-11-10 13:26 UTC, SleepWalker commented
You'll get TS errors after this PR if your project doesn't depend from all the schema libs used for typings:

![image](https://user-images.githubusercontent.com/2536916/201103058-ab677bcc-2e21-4962-a8ef-1a7c731759ee.png)