docs: adding reference guide
fastify/env-schema pull request #144
Opened 2022-12-25 09:51 UTC by lirantal

Adding a section to list helpful resource guides to get started with building with env-schema

Fixes #142 

#### Checklist

- [ ] run `npm run test` and `npm run benchmark`
- [ ] tests and/or benchmarks are included
- [ ] documentation is changed or added
- [ ] commit message and code follows the [Developer's Certification of Origin](https://github.com/fastify/.github/blob/master/CONTRIBUTING.md#developers-certificate-of-origin-11)
      and the [Code of conduct](https://github.com/fastify/.github/blob/master/CODE_OF_CONDUCT.md)

2022-12-25 22:36 UTC, mcollina commented
Could you split creation of the Fastify application with the call to listen in two files, as this enables testing without using globals?

2022-12-26 10:51 UTC, lirantal commented
Sure thing. I was going for simplicity there but have merged a PR to change that to a more modular structure: https://github.com/lirantal/fastify-dotenv-envschema-example/pull/1 (landed in `main` already)

2022-12-26 15:36 UTC, Fdawgs requested changes

2022-12-26 15:36 UTC, Fdawgs commented on README.md
> +See [supporting resources](#supporting-resources) section for helpful guides on getting started
```suggestion
See [supporting resources](#supporting-resources) section for helpful guides on getting started.
```

2022-12-26 19:08 UTC, lirantal commented on README.md
> +See [supporting resources](#supporting-resources) section for helpful guides on getting started
Good catch!

2022-12-26 19:12 UTC, Fdawgs approved these changes

2022-12-26 19:28 UTC, climba03003 reviewed
Shouldn't it place in `@fastify/env` when you did not directly using `env-schema`?

2022-12-26 19:32 UTC, lirantal commented
It's a good question and I was asking myself the same thing but I thought the ideal place is here because folks using the `@fastify/env` plugin would probably already know best practices and how to use it, yet new folks landing on this repository might look for how to get started and how they can use `env-schema`, especially since it doesn't have anything to do with Fastify as the app framework itself, but just happens to live on this org.

So, I'd keep it here to be more helpful but happy to move elsewhere if you think it'd be a better fit.

2022-12-28 18:33 UTC, mcollina commented
I personally find env-schema better and I don't use fastify-env ;).

2022-12-30 10:50 UTC, lirantal commented
fastify-env is pretty small and is anyway just a wrapper around env-schema though, isn't it? I figured if you don't use fastify-env you probably just do the same plugging wrapping yourself.

2022-12-30 11:22 UTC, mcollina commented
I tend to _not_ wrap this into a plugin, but rather read it before Fastify is started. In this way I can customize the options of Fastify itself

2022-12-30 15:01 UTC, jsumners commented
> I tend to _not_ wrap this into a plugin, but rather read it before Fastify is started. In this way I can customize the options of Fastify itself

Agreed. I really don't understand the point of `fastify-env`. 

```js
'use strict'

const dotenv = require('dotenv')
const config = dotenv.config()

const fastify = require('fastify')({ /* use stuff from config */})
fastify.decorate('env', {
  getter() { return config }
})
```

2023-07-31 08:51 UTC, mcollina approved these changes
lgtm

2023-07-31 08:51 UTC, merged